/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LEGION
 */
public class HalamanUtama extends javax.swing.JFrame {

    /**
     * Creates new form HalamanUtama
     */
    public HalamanUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btKeluar = new javax.swing.JButton();
        btCust = new javax.swing.JButton();
        btBarang = new javax.swing.JButton();
        btSupplier = new javax.swing.JButton();
        btJual = new javax.swing.JButton();
        btBeli = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("SELAMAT DATANG, ADMIN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 40, 470, 40);

        jLabel4.setFont(new java.awt.Font("Digital-7 Mono", 0, 70)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(92, 225, 230));
        jLabel4.setText("ZERO | MART");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(540, 40, 450, 70);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("HALAMAN UTAMA");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 90, 340, 60);

        btKeluar.setBackground(new java.awt.Color(92, 225, 230));
        btKeluar.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btKeluar.setText("KELUAR");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btKeluar);
        btKeluar.setBounds(750, 480, 180, 60);

        btCust.setBackground(new java.awt.Color(92, 225, 230));
        btCust.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btCust.setText("DATA CUSTOMER");
        btCust.setAlignmentX(0.5F);
        btCust.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCustActionPerformed(evt);
            }
        });
        jPanel1.add(btCust);
        btCust.setBounds(80, 210, 250, 80);

        btBarang.setBackground(new java.awt.Color(92, 225, 230));
        btBarang.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btBarang.setText("DATA BARANG");
        btBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBarangActionPerformed(evt);
            }
        });
        jPanel1.add(btBarang);
        btBarang.setBounds(380, 210, 250, 80);

        btSupplier.setBackground(new java.awt.Color(92, 225, 230));
        btSupplier.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btSupplier.setText("DATA SUPPLIER");
        btSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupplierActionPerformed(evt);
            }
        });
        jPanel1.add(btSupplier);
        btSupplier.setBounds(690, 210, 250, 80);

        btJual.setBackground(new java.awt.Color(92, 225, 230));
        btJual.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btJual.setText("DATA PENJUALAN");
        btJual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btJualActionPerformed(evt);
            }
        });
        jPanel1.add(btJual);
        btJual.setBounds(80, 350, 250, 80);

        btBeli.setBackground(new java.awt.Color(92, 225, 230));
        btBeli.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btBeli.setText("DATA PEMBELIAN");
        btBeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBeliActionPerformed(evt);
            }
        });
        jPanel1.add(btBeli);
        btBeli.setBounds(380, 350, 250, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Back.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 0, 1030, 580);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btKeluarActionPerformed

    private void btCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCustActionPerformed
        Customer n = new Customer();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btCustActionPerformed

    private void btBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBarangActionPerformed
       Barang n = new Barang();
       n.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btBarangActionPerformed

    private void btSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupplierActionPerformed
        Supplier n = new Supplier();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btSupplierActionPerformed

    private void btJualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btJualActionPerformed
        Penjualan n = new Penjualan();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btJualActionPerformed

    private void btBeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBeliActionPerformed
        Pembelian n = new Pembelian();
        n.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btBeliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HalamanUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HalamanUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBarang;
    private javax.swing.JButton btBeli;
    private javax.swing.JButton btCust;
    private javax.swing.JButton btJual;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btSupplier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
