
import java.awt.HeadlessException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LEGION
 */
public class Pembelian extends javax.swing.JFrame {

    /**
     * Creates new form Barang
     */
    
    public void Kosong(){
    txtIDSup.setEditable(true);
    txtIDSup.setText(null);
    cbIDBarang.setSelectedItem(this);
    cbIDSup.setSelectedItem(this);
    txtTglJual.setText(null);
    txtJumJual.setText(null);
    txtHargaJual.setText(null);
    }
    
    public Pembelian() {
        initComponents();
        tampil();
    }

        public void tampil() {
        DefaultTableModel model= new DefaultTableModel();
        model.addColumn("No");
        model.addColumn("Kode Beli");
        model.addColumn("Kode Barang");
        model.addColumn("Kode Supplier");
        model.addColumn("Tanggal Jual");
        model.addColumn("Jumlah Jual");
        model.addColumn("Harga Jual");
        
        try{
            int no=1;
            String sql="select * from beli";
            java.sql.Connection MySQLConfig = (Connection)Konfig.ConfigDB();
            java.sql.Statement stm=MySQLConfig.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{
                no++,
                res.getString(1),
                res.getString(2),
                res.getString(3),
                res.getString(4),
                res.getString(5),
                res.getString(6)});
            }
            tableJual.setModel(model);
            }catch(SQLException e){
                System.out.println("Error boss "+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableJual = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtIDSup = new javax.swing.JTextField();
        txtTglJual = new javax.swing.JTextField();
        txtJumJual = new javax.swing.JTextField();
        btTambah = new javax.swing.JButton();
        btUbah = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btCetak = new javax.swing.JButton();
        btHalaman = new javax.swing.JButton();
        btKeluar = new javax.swing.JButton();
        cbIDBarang = new javax.swing.JComboBox<>();
        cbIDSup = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txtHargaJual = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 576));
        jPanel1.setLayout(null);

        tableJual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableJual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJualMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableJual);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 108, 660, 380);

        jLabel2.setFont(new java.awt.Font("Digital-7 Mono", 0, 70)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(92, 225, 230));
        jLabel2.setText("ZERO | MART");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(510, 20, 490, 70);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 50)); // NOI18N
        jLabel3.setText("DATA PEMBELIAN");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 10, 480, 90);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("KODE BELI                    =");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 110, 170, 20);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("KODE BARANG              =");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 150, 170, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("KODE CUSTOMER          =");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 190, 170, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("TANGGAL BELI             =");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 230, 170, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setText("JUMLAH BELI               =");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 270, 170, 17);

        txtIDSup.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtIDSup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDSupActionPerformed(evt);
            }
        });
        jPanel1.add(txtIDSup);
        txtIDSup.setBounds(200, 110, 140, 20);

        txtTglJual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtTglJual);
        txtTglJual.setBounds(200, 230, 140, 23);

        txtJumJual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtJumJual);
        txtJumJual.setBounds(200, 270, 140, 23);

        btTambah.setBackground(new java.awt.Color(92, 225, 224));
        btTambah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btTambah.setText("TAMBAH");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });
        jPanel1.add(btTambah);
        btTambah.setBounds(50, 360, 110, 50);

        btUbah.setBackground(new java.awt.Color(92, 225, 230));
        btUbah.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btUbah.setText("UBAH");
        btUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUbahActionPerformed(evt);
            }
        });
        jPanel1.add(btUbah);
        btUbah.setBounds(190, 360, 110, 50);

        btHapus.setBackground(new java.awt.Color(92, 225, 230));
        btHapus.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btHapus.setText("HAPUS");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });
        jPanel1.add(btHapus);
        btHapus.setBounds(50, 440, 110, 50);

        btCetak.setBackground(new java.awt.Color(92, 225, 230));
        btCetak.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btCetak.setText("CETAK");
        btCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCetakActionPerformed(evt);
            }
        });
        jPanel1.add(btCetak);
        btCetak.setBounds(190, 440, 110, 50);

        btHalaman.setBackground(new java.awt.Color(92, 225, 230));
        btHalaman.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btHalaman.setText("HALAMAN");
        btHalaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHalamanActionPerformed(evt);
            }
        });
        jPanel1.add(btHalaman);
        btHalaman.setBounds(730, 500, 110, 60);

        btKeluar.setBackground(new java.awt.Color(92, 225, 230));
        btKeluar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        btKeluar.setText("KELUAR");
        btKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btKeluar);
        btKeluar.setBounds(870, 500, 110, 60);

        cbIDBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BG-1" }));
        cbIDBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbIDBarangActionPerformed(evt);
            }
        });
        jPanel1.add(cbIDBarang);
        cbIDBarang.setBounds(200, 150, 140, 20);

        cbIDSup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CS-3" }));
        jPanel1.add(cbIDSup);
        cbIDSup.setBounds(200, 190, 140, 20);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("HARGA BELI                 =");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 310, 170, 17);

        txtHargaJual.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel1.add(txtHargaJual);
        txtHargaJual.setBounds(200, 310, 140, 23);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 0, 0);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btHalamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHalamanActionPerformed
       HalamanUtama n = new HalamanUtama();
       n.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btHalamanActionPerformed

    private void btKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKeluarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btKeluarActionPerformed

    private void tableJualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJualMouseClicked
        txtIDSup.setEditable(false);
        
        int baris= tableJual.rowAtPoint(evt.getPoint());
            String kode_jual=tableJual.getValueAt(baris,1).toString();
            txtIDSup.setText(kode_jual);
            String kode_barang=tableJual.getValueAt(baris,2).toString();
            cbIDBarang.setSelectedItem(kode_barang);
            String kode_supplier=tableJual.getValueAt(baris,3).toString();
            cbIDSup.setSelectedItem(kode_supplier);
            String tgl_jual=tableJual.getValueAt(baris,4).toString();
            txtTglJual.setText(tgl_jual);
            String jml_jual=tableJual.getValueAt(baris,5).toString();
            txtJumJual.setText(jml_jual);
            String harga_jual=tableJual.getValueAt(baris,6).toString();
            txtHargaJual.setText(harga_jual);
    }//GEN-LAST:event_tableJualMouseClicked

    private void btUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUbahActionPerformed
        try{
            String sql="UPDATE beli SET kode_beli='"+txtIDSup.getText()+"',"
                    +"kode_barang='"+cbIDBarang.getSelectedItem()+"',"
                    +"kode_customer='"+cbIDSup.getSelectedItem()+"',"
                    +"tgl_beli='"+txtTglJual.getText()+"',"
                    +"jml_beli='"+txtJumJual.getText()+"',"
                    +"harga_beli='"+txtHargaJual.getText()+"' WHERE kode_beli='"+txtIDSup.getText()+"'";
                    
               java.sql.Connection MySQLConfig = (Connection)Konfig.ConfigDB();
               java.sql.PreparedStatement pstm=MySQLConfig.prepareStatement(sql);
               pstm.execute();
               JOptionPane.showMessageDialog(null,"UPDATE Data BErhasil ");
               tampil();
               Kosong();
        }catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btUbahActionPerformed

    private void cbIDBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbIDBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbIDBarangActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
        try{
            String sql="DELETE FROM beli WHERE kode_beli='"+txtIDSup.getText()+"'";
            
            java.sql.Connection MySQLConfig = (Connection)Konfig.ConfigDB();
            java.sql.PreparedStatement pstm=MySQLConfig.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Hapus Data Berhasil");
            tampil();
            Kosong();
        }catch(HeadlessException |  SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btHapusActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        try{
            String sql="INSERT INTO beli VALUES('"+txtIDSup.getText()+"',"
                    +"'"+cbIDBarang.getSelectedItem()+"',"
                    +"'"+cbIDSup.getSelectedItem()+"',"
                    +"'"+txtTglJual.getText()+"',"
                    +"'"+txtJumJual.getText()+"',"
                    +"'"+txtHargaJual.getText()+"')";
            
            java.sql.Connection MySQLConfig = (Connection)Konfig.ConfigDB();
            java.sql.PreparedStatement pstm=MySQLConfig.prepareStatement(sql);
            pstm.execute();
            JOptionPane.showMessageDialog(null,"Simpan Data Berhasil");
            tampil();
            Kosong();
         }catch(HeadlessException |  SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_btTambahActionPerformed

    private void btCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCetakActionPerformed
        try{
            InputStream is = Pembelian.class.getResourceAsStream("/cetak/beli.jasper");
            JasperPrint jsPrint = JasperFillManager.fillReport(is, null , Konfig.ConfigDB());
            JasperViewer.viewReport(jsPrint,false);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,"Gagal masuk karena : "+e.getMessage(),"Cetak laporan",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btCetakActionPerformed

    private void txtIDSupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDSupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDSupActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCetak;
    private javax.swing.JButton btHalaman;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btKeluar;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton btUbah;
    private javax.swing.JComboBox<String> cbIDBarang;
    private javax.swing.JComboBox<String> cbIDSup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJual;
    private javax.swing.JTextField txtHargaJual;
    private javax.swing.JTextField txtIDSup;
    private javax.swing.JTextField txtJumJual;
    private javax.swing.JTextField txtTglJual;
    // End of variables declaration//GEN-END:variables
}
